### ISSUE TITLE
Not really an 'issue' but a code request

### ISSUE THREAD

**Issue by fdepaolis** [njtierney/rstudioconf20#9]
I've come across your RStudio 2020 presentation on longitudinal data and found it very useful. Do you have the complete R code for all the processes you showed? Thank you very much

Fernando DePaolis, Ph.D.
Middlebury Institute - California USA

**Comment by njtierney** [comment]
Hi there! Thanks!

I do - it's all here: https://github.com/njtierney/rstudioconf20/blob/master/slides/index.Rmd

This whole repository should contain everything you need 😄

**Comment by fdepaolis** [comment]
Thank you very much!! Looking forward to enjoying your next presentation.
Cheers,

Fernando DePaolis
